version: '3.8'

services:
  app:
    build: .
    container_name: socketio-chat-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CLIENT_URL=https://your-domain.com
      - JWT_SECRET=${JWT_SECRET}
      - RATE_LIMIT_MAX=100
    volumes:
      - ./server/uploads:/app/server/uploads
      - ./server/logs:/app/server/logs
    networks:
      - chat-network
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { hostname: 'localhost', port: 5000, path: '/api/health', timeout: 2000 }; const req = http.request(options, (res) => { process.exit(res.statusCode === 200 ? 0 : 1); }); req.on('error', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: socketio-chat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  uploads:
  logs: